const mongoose = require('../index');
const dayjs = require('dayjs');
//定义添加班级数据结构
const studentClass = mongoose.Schema({
    className:{//班级名称
        type:String,
        require:true,
        index:true
    },
    headTeacher:{//班主任姓名
        type:String,
        require:true,
        index:true
    },
    headTeacherId:{//班主任编号
        type:String,
        require:true,
        index:true
    },
    classNumber:{//班级人数
        type:String,
        require:true,
    },
    classId:{//班级id
        type:Number,
        require:true,
        default:1
    },
    chineseId:{//语文老师编号
        type:String,
        require:true,
    },
    chineseName:{//语文老师姓名
        type:String,
        require:true,
    },
    mathId:{//数学老师编号
        type:String,
        require:true,
    },
    mathName:{//数学老师姓名
        type:String,
        require:true,
    },
    englishId:{//英语老师编号
        type:String,
        require:true,
    },
    englishName:{//英语老师姓名
        type:String,
        require:true,
    },
    cphysicalId:{//物理老师编号
        type:String,
        require:true,
    },
    cphysicalName:{//物理老师姓名
        type:String,
        require:true,
    },
    chemistryId:{//化学老师编号
        type:String,
        require:true,
    },
    chemistryName:{//化学老师姓名
        type:String,
        require:true,
    },
    biologicalId:{//生物老师编号
        type:String,
        require:true,
    },
    biologicalName:{//生物老师姓名
        type:String,
        require:true,
    },
    geographyId:{//地理老师编号
        type:String,
        require:true,
    },
    geographyName:{//地理老师姓名
        type:String,
        require:true,
    },
    historyId:{//历史老师编号
        type:String,
        require:true,
    },
    historyName:{//历史老师姓名
        type:String,
        require:true,
    },
    politicalId:{//政治老师编号
        type:String,
        require:true,
    },
    politicalName:{//政治老师姓名
        type:String,
        require:true,
    },
    createTime:{//创建时间
        type:String,
        default:dayjs().format('YYYY-MM-DD HH:mm:ss')
    }
    
  })  

  module.exports = mongoose.model('StudentClass', studentClass,'studentClass')